/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiagnosticReport
 */
export interface DiagnosticReport {
    /**
     * 
     * @type {string}
     * @memberof DiagnosticReport
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticReport
     */
    sampleId: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticReport
     */
    patientId?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticReport
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticReport
     */
    conclusion: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticReport
     */
    recommendations?: string;
    /**
     * 
     * @type {Date}
     * @memberof DiagnosticReport
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof DiagnosticReport
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof DiagnosticReport
     */
    finalizedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticReport
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticReport
     */
    status: DiagnosticReportStatusEnum;
}


/**
 * @export
 */
export const DiagnosticReportStatusEnum = {
    Draft: 'draft',
    Finalized: 'finalized'
} as const;
export type DiagnosticReportStatusEnum = typeof DiagnosticReportStatusEnum[keyof typeof DiagnosticReportStatusEnum];


/**
 * Check if a given object implements the DiagnosticReport interface.
 */
export function instanceOfDiagnosticReport(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "sampleId" in value;
    isInstance = isInstance && "summary" in value;
    isInstance = isInstance && "conclusion" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function DiagnosticReportFromJSON(json: any): DiagnosticReport {
    return DiagnosticReportFromJSONTyped(json, false);
}

export function DiagnosticReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticReport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sampleId': json['sampleId'],
        'patientId': !exists(json, 'patientId') ? undefined : json['patientId'],
        'summary': json['summary'],
        'conclusion': json['conclusion'],
        'recommendations': !exists(json, 'recommendations') ? undefined : json['recommendations'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'finalizedAt': !exists(json, 'finalizedAt') ? undefined : (new Date(json['finalizedAt'])),
        'author': !exists(json, 'author') ? undefined : json['author'],
        'status': json['status'],
    };
}

export function DiagnosticReportToJSON(value?: DiagnosticReport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'sampleId': value.sampleId,
        'patientId': value.patientId,
        'summary': value.summary,
        'conclusion': value.conclusion,
        'recommendations': value.recommendations,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'finalizedAt': value.finalizedAt === undefined ? undefined : (value.finalizedAt.toISOString()),
        'author': value.author,
        'status': value.status,
    };
}

