/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MeasurementValue } from './MeasurementValue';
import {
    MeasurementValueFromJSON,
    MeasurementValueFromJSONTyped,
    MeasurementValueToJSON,
} from './MeasurementValue';

/**
 * 
 * @export
 * @interface MeasurementValuesUpdate
 */
export interface MeasurementValuesUpdate {
    /**
     * 
     * @type {Array<MeasurementValue>}
     * @memberof MeasurementValuesUpdate
     */
    measurements: Array<MeasurementValue>;
}

/**
 * Check if a given object implements the MeasurementValuesUpdate interface.
 */
export function instanceOfMeasurementValuesUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "measurements" in value;

    return isInstance;
}

export function MeasurementValuesUpdateFromJSON(json: any): MeasurementValuesUpdate {
    return MeasurementValuesUpdateFromJSONTyped(json, false);
}

export function MeasurementValuesUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasurementValuesUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'measurements': ((json['measurements'] as Array<any>).map(MeasurementValueFromJSON)),
    };
}

export function MeasurementValuesUpdateToJSON(value?: MeasurementValuesUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'measurements': ((value.measurements as Array<any>).map(MeasurementValueToJSON)),
    };
}

