/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MeasurementValueType } from './MeasurementValueType';
import {
    MeasurementValueTypeFromJSON,
    MeasurementValueTypeFromJSONTyped,
    MeasurementValueTypeToJSON,
} from './MeasurementValueType';

/**
 * 
 * @export
 * @interface MeasurementDefinition
 */
export interface MeasurementDefinition {
    /**
     * 
     * @type {string}
     * @memberof MeasurementDefinition
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof MeasurementDefinition
     */
    label: string;
    /**
     * 
     * @type {MeasurementValueType}
     * @memberof MeasurementDefinition
     */
    valueType: MeasurementValueType;
    /**
     * 
     * @type {string}
     * @memberof MeasurementDefinition
     */
    unit?: string;
    /**
     * 
     * @type {number}
     * @memberof MeasurementDefinition
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementDefinition
     */
    max?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof MeasurementDefinition
     */
    options?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof MeasurementDefinition
     */
    required?: boolean;
}

/**
 * Check if a given object implements the MeasurementDefinition interface.
 */
export function instanceOfMeasurementDefinition(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "valueType" in value;

    return isInstance;
}

export function MeasurementDefinitionFromJSON(json: any): MeasurementDefinition {
    return MeasurementDefinitionFromJSONTyped(json, false);
}

export function MeasurementDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasurementDefinition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'label': json['label'],
        'valueType': MeasurementValueTypeFromJSON(json['valueType']),
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
        'min': !exists(json, 'min') ? undefined : json['min'],
        'max': !exists(json, 'max') ? undefined : json['max'],
        'options': !exists(json, 'options') ? undefined : json['options'],
        'required': !exists(json, 'required') ? undefined : json['required'],
    };
}

export function MeasurementDefinitionToJSON(value?: MeasurementDefinition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'label': value.label,
        'valueType': MeasurementValueTypeToJSON(value.valueType),
        'unit': value.unit,
        'min': value.min,
        'max': value.max,
        'options': value.options,
        'required': value.required,
    };
}

