/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MeasurementValueType = {
    Number: 'number',
    Text: 'text',
    Boolean: 'boolean',
    Select: 'select'
} as const;
export type MeasurementValueType = typeof MeasurementValueType[keyof typeof MeasurementValueType];


export function MeasurementValueTypeFromJSON(json: any): MeasurementValueType {
    return MeasurementValueTypeFromJSONTyped(json, false);
}

export function MeasurementValueTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasurementValueType {
    return json as MeasurementValueType;
}

export function MeasurementValueTypeToJSON(value?: MeasurementValueType | null): any {
    return value as any;
}

