/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeasurementValue
 */
export interface MeasurementValue {
    /**
     * 
     * @type {string}
     * @memberof MeasurementValue
     */
    testTypeCode: string;
    /**
     * 
     * @type {string}
     * @memberof MeasurementValue
     */
    code: string;
    /**
     * Serialized measurement value. Interpret the value according to the referenced MeasurementDefinition.valueType.
     * @type {string}
     * @memberof MeasurementValue
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof MeasurementValue
     */
    unit?: string;
    /**
     * 
     * @type {Date}
     * @memberof MeasurementValue
     */
    measuredAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof MeasurementValue
     */
    enteredByRole?: MeasurementValueEnteredByRoleEnum;
}


/**
 * @export
 */
export const MeasurementValueEnteredByRoleEnum = {
    Technician: 'technician',
    Diagnostician: 'diagnostician'
} as const;
export type MeasurementValueEnteredByRoleEnum = typeof MeasurementValueEnteredByRoleEnum[keyof typeof MeasurementValueEnteredByRoleEnum];


/**
 * Check if a given object implements the MeasurementValue interface.
 */
export function instanceOfMeasurementValue(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "testTypeCode" in value;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function MeasurementValueFromJSON(json: any): MeasurementValue {
    return MeasurementValueFromJSONTyped(json, false);
}

export function MeasurementValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasurementValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'testTypeCode': json['testTypeCode'],
        'code': json['code'],
        'value': json['value'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
        'measuredAt': !exists(json, 'measuredAt') ? undefined : (new Date(json['measuredAt'])),
        'enteredByRole': !exists(json, 'enteredByRole') ? undefined : json['enteredByRole'],
    };
}

export function MeasurementValueToJSON(value?: MeasurementValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'testTypeCode': value.testTypeCode,
        'code': value.code,
        'value': value.value,
        'unit': value.unit,
        'measuredAt': value.measuredAt === undefined ? undefined : (value.measuredAt.toISOString()),
        'enteredByRole': value.enteredByRole,
    };
}

