/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewSample
 */
export interface NewSample {
    /**
     * 
     * @type {string}
     * @memberof NewSample
     */
    patientName: string;
    /**
     * 
     * @type {string}
     * @memberof NewSample
     */
    patientId: string;
    /**
     * 
     * @type {string}
     * @memberof NewSample
     */
    sampleCode: string;
    /**
     * 
     * @type {Date}
     * @memberof NewSample
     */
    collectedAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewSample
     */
    testTypes: Array<string>;
}

/**
 * Check if a given object implements the NewSample interface.
 */
export function instanceOfNewSample(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "patientName" in value;
    isInstance = isInstance && "patientId" in value;
    isInstance = isInstance && "sampleCode" in value;
    isInstance = isInstance && "collectedAt" in value;
    isInstance = isInstance && "testTypes" in value;

    return isInstance;
}

export function NewSampleFromJSON(json: any): NewSample {
    return NewSampleFromJSONTyped(json, false);
}

export function NewSampleFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSample {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientName': json['patientName'],
        'patientId': json['patientId'],
        'sampleCode': json['sampleCode'],
        'collectedAt': (new Date(json['collectedAt'])),
        'testTypes': json['testTypes'],
    };
}

export function NewSampleToJSON(value?: NewSample | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patientName': value.patientName,
        'patientId': value.patientId,
        'sampleCode': value.sampleCode,
        'collectedAt': (value.collectedAt.toISOString()),
        'testTypes': value.testTypes,
    };
}
