/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReportDraft
 */
export interface ReportDraft {
    /**
     * 
     * @type {string}
     * @memberof ReportDraft
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof ReportDraft
     */
    conclusion: string;
    /**
     * 
     * @type {string}
     * @memberof ReportDraft
     */
    recommendations?: string;
}

/**
 * Check if a given object implements the ReportDraft interface.
 */
export function instanceOfReportDraft(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "summary" in value;
    isInstance = isInstance && "conclusion" in value;

    return isInstance;
}

export function ReportDraftFromJSON(json: any): ReportDraft {
    return ReportDraftFromJSONTyped(json, false);
}

export function ReportDraftFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportDraft {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'summary': json['summary'],
        'conclusion': json['conclusion'],
        'recommendations': !exists(json, 'recommendations') ? undefined : json['recommendations'],
    };
}

export function ReportDraftToJSON(value?: ReportDraft | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'summary': value.summary,
        'conclusion': value.conclusion,
        'recommendations': value.recommendations,
    };
}

