/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiagnosticReport } from './DiagnosticReport';
import {
    DiagnosticReportFromJSON,
    DiagnosticReportFromJSONTyped,
    DiagnosticReportToJSON,
} from './DiagnosticReport';
import type { MeasurementValue } from './MeasurementValue';
import {
    MeasurementValueFromJSON,
    MeasurementValueFromJSONTyped,
    MeasurementValueToJSON,
} from './MeasurementValue';
import type { SampleStatus } from './SampleStatus';
import {
    SampleStatusFromJSON,
    SampleStatusFromJSONTyped,
    SampleStatusToJSON,
} from './SampleStatus';

/**
 * 
 * @export
 * @interface Sample
 */
export interface Sample {
    /**
     * 
     * @type {string}
     * @memberof Sample
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Sample
     */
    patientName: string;
    /**
     * 
     * @type {string}
     * @memberof Sample
     */
    patientId?: string;
    /**
     * 
     * @type {string}
     * @memberof Sample
     */
    sampleCode: string;
    /**
     * 
     * @type {Date}
     * @memberof Sample
     */
    collectedAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof Sample
     */
    testTypes: Array<string>;
    /**
     * 
     * @type {SampleStatus}
     * @memberof Sample
     */
    status: SampleStatus;
    /**
     * 
     * @type {Array<MeasurementValue>}
     * @memberof Sample
     */
    measurements: Array<MeasurementValue>;
    /**
     * 
     * @type {DiagnosticReport}
     * @memberof Sample
     */
    report?: DiagnosticReport;
    /**
     * 
     * @type {Date}
     * @memberof Sample
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Sample
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Sample
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof Sample
     */
    finalizedBy?: string;
}

/**
 * Check if a given object implements the Sample interface.
 */
export function instanceOfSample(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "patientName" in value;
    isInstance = isInstance && "sampleCode" in value;
    isInstance = isInstance && "collectedAt" in value;
    isInstance = isInstance && "testTypes" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "measurements" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function SampleFromJSON(json: any): Sample {
    return SampleFromJSONTyped(json, false);
}

export function SampleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sample {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'patientName': json['patientName'],
        'patientId': !exists(json, 'patientId') ? undefined : json['patientId'],
        'sampleCode': json['sampleCode'],
        'collectedAt': (new Date(json['collectedAt'])),
        'testTypes': json['testTypes'],
        'status': SampleStatusFromJSON(json['status']),
        'measurements': ((json['measurements'] as Array<any>).map(MeasurementValueFromJSON)),
        'report': !exists(json, 'report') ? undefined : DiagnosticReportFromJSON(json['report']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'finalizedBy': !exists(json, 'finalizedBy') ? undefined : json['finalizedBy'],
    };
}

export function SampleToJSON(value?: Sample | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'patientName': value.patientName,
        'patientId': value.patientId,
        'sampleCode': value.sampleCode,
        'collectedAt': (value.collectedAt.toISOString()),
        'testTypes': value.testTypes,
        'status': SampleStatusToJSON(value.status),
        'measurements': ((value.measurements as Array<any>).map(MeasurementValueToJSON)),
        'report': DiagnosticReportToJSON(value.report),
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'createdBy': value.createdBy,
        'finalizedBy': value.finalizedBy,
    };
}

