/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SampleStatus } from './SampleStatus';
import {
    SampleStatusFromJSON,
    SampleStatusFromJSONTyped,
    SampleStatusToJSON,
} from './SampleStatus';

/**
 * 
 * @export
 * @interface SampleStatusUpdate
 */
export interface SampleStatusUpdate {
    /**
     * 
     * @type {SampleStatus}
     * @memberof SampleStatusUpdate
     */
    status: SampleStatus;
}

/**
 * Check if a given object implements the SampleStatusUpdate interface.
 */
export function instanceOfSampleStatusUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function SampleStatusUpdateFromJSON(json: any): SampleStatusUpdate {
    return SampleStatusUpdateFromJSONTyped(json, false);
}

export function SampleStatusUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SampleStatusUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': SampleStatusFromJSON(json['status']),
    };
}

export function SampleStatusUpdateToJSON(value?: SampleStatusUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': SampleStatusToJSON(value.status),
    };
}

