/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SampleStatus = {
    Draft: 'draft',
    Collected: 'collected',
    InDiagnostics: 'in_diagnostics',
    ReportDraft: 'report_draft',
    Finalized: 'finalized',
    Tainted: 'tainted'
} as const;
export type SampleStatus = typeof SampleStatus[keyof typeof SampleStatus];


export function SampleStatusFromJSON(json: any): SampleStatus {
    return SampleStatusFromJSONTyped(json, false);
}

export function SampleStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SampleStatus {
    return json as SampleStatus;
}

export function SampleStatusToJSON(value?: SampleStatus | null): any {
    return value as any;
}

