/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MeasurementDefinition } from './MeasurementDefinition';
import {
    MeasurementDefinitionFromJSON,
    MeasurementDefinitionFromJSONTyped,
    MeasurementDefinitionToJSON,
} from './MeasurementDefinition';

/**
 * 
 * @export
 * @interface TestType
 */
export interface TestType {
    /**
     * 
     * @type {string}
     * @memberof TestType
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof TestType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TestType
     */
    description?: string;
    /**
     * 
     * @type {Array<MeasurementDefinition>}
     * @memberof TestType
     */
    measurementSchema: Array<MeasurementDefinition>;
}

/**
 * Check if a given object implements the TestType interface.
 */
export function instanceOfTestType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "measurementSchema" in value;

    return isInstance;
}

export function TestTypeFromJSON(json: any): TestType {
    return TestTypeFromJSONTyped(json, false);
}

export function TestTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'measurementSchema': ((json['measurementSchema'] as Array<any>).map(MeasurementDefinitionFromJSON)),
    };
}

export function TestTypeToJSON(value?: TestType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'name': value.name,
        'description': value.description,
        'measurementSchema': ((value.measurementSchema as Array<any>).map(MeasurementDefinitionToJSON)),
    };
}

