/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Sample,
} from '../models';
import {
    SampleFromJSON,
    SampleToJSON,
} from '../models';

export interface GetPatientReportsRequest {
    patientId: string;
    testType?: string;
    limit?: number;
}

/**
 * PatientReportsApi - interface
 * 
 * @export
 * @interface PatientReportsApiInterface
 */
export interface PatientReportsApiInterface {
    /**
     * 
     * @summary Provides finalized reports for a patient
     * @param {string} patientId Patient identifier used for finalized report lookup.
     * @param {string} [testType] Optional test type code filter.
     * @param {number} [limit] Maximum number of finalized reports to return.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientReportsApiInterface
     */
    getPatientReportsRaw(requestParameters: GetPatientReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Sample>>>;

    /**
     * Provides finalized reports for a patient
     */
    getPatientReports(requestParameters: GetPatientReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Sample>>;

}

/**
 * 
 */
export class PatientReportsApi extends runtime.BaseAPI implements PatientReportsApiInterface {

    /**
     * Provides finalized reports for a patient
     */
    async getPatientReportsRaw(requestParameters: GetPatientReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Sample>>> {
        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling getPatientReports.');
        }

        const queryParameters: any = {};

        if (requestParameters.testType !== undefined) {
            queryParameters['testType'] = requestParameters.testType;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/patients/{patientId}/reports`.replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters.patientId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SampleFromJSON));
    }

    /**
     * Provides finalized reports for a patient
     */
    async getPatientReports(requestParameters: GetPatientReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Sample>> {
        const response = await this.getPatientReportsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
