/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MeasurementValuesUpdate,
  Sample,
} from '../models';
import {
    MeasurementValuesUpdateFromJSON,
    MeasurementValuesUpdateToJSON,
    SampleFromJSON,
    SampleToJSON,
} from '../models';

export interface SaveSampleMeasurementsRequest {
    sampleId: string;
    measurementValuesUpdate: MeasurementValuesUpdate;
}

/**
 * SampleMeasurementsApi - interface
 * 
 * @export
 * @interface SampleMeasurementsApiInterface
 */
export interface SampleMeasurementsApiInterface {
    /**
     * 
     * @summary Saves measured values for a sample
     * @param {string} sampleId System identifier of the sample.
     * @param {MeasurementValuesUpdate} measurementValuesUpdate Measurement values matching the selected test type schemas.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleMeasurementsApiInterface
     */
    saveSampleMeasurementsRaw(requestParameters: SaveSampleMeasurementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>>;

    /**
     * Saves measured values for a sample
     */
    saveSampleMeasurements(requestParameters: SaveSampleMeasurementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample>;

}

/**
 * 
 */
export class SampleMeasurementsApi extends runtime.BaseAPI implements SampleMeasurementsApiInterface {

    /**
     * Saves measured values for a sample
     */
    async saveSampleMeasurementsRaw(requestParameters: SaveSampleMeasurementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>> {
        if (requestParameters.sampleId === null || requestParameters.sampleId === undefined) {
            throw new runtime.RequiredError('sampleId','Required parameter requestParameters.sampleId was null or undefined when calling saveSampleMeasurements.');
        }

        if (requestParameters.measurementValuesUpdate === null || requestParameters.measurementValuesUpdate === undefined) {
            throw new runtime.RequiredError('measurementValuesUpdate','Required parameter requestParameters.measurementValuesUpdate was null or undefined when calling saveSampleMeasurements.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/samples/{sampleId}/measurements`.replace(`{${"sampleId"}}`, encodeURIComponent(String(requestParameters.sampleId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MeasurementValuesUpdateToJSON(requestParameters.measurementValuesUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleFromJSON(jsonValue));
    }

    /**
     * Saves measured values for a sample
     */
    async saveSampleMeasurements(requestParameters: SaveSampleMeasurementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample> {
        const response = await this.saveSampleMeasurementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
