/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReportDraft,
  Sample,
} from '../models';
import {
    ReportDraftFromJSON,
    ReportDraftToJSON,
    SampleFromJSON,
    SampleToJSON,
} from '../models';

export interface DeleteSampleReportRequest {
    sampleId: string;
}

export interface FinalizeSampleReportRequest {
    sampleId: string;
}

export interface SaveSampleReportRequest {
    sampleId: string;
    reportDraft: ReportDraft;
}

/**
 * SampleReportsApi - interface
 * 
 * @export
 * @interface SampleReportsApiInterface
 */
export interface SampleReportsApiInterface {
    /**
     * 
     * @summary Discards a preliminary diagnostic report
     * @param {string} sampleId System identifier of the sample.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleReportsApiInterface
     */
    deleteSampleReportRaw(requestParameters: DeleteSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>>;

    /**
     * Discards a preliminary diagnostic report
     */
    deleteSampleReport(requestParameters: DeleteSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample>;

    /**
     * 
     * @summary Finalizes the diagnostic report
     * @param {string} sampleId System identifier of the sample.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleReportsApiInterface
     */
    finalizeSampleReportRaw(requestParameters: FinalizeSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>>;

    /**
     * Finalizes the diagnostic report
     */
    finalizeSampleReport(requestParameters: FinalizeSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample>;

    /**
     * 
     * @summary Saves a preliminary diagnostic report
     * @param {string} sampleId System identifier of the sample.
     * @param {ReportDraft} reportDraft Preliminary report content.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleReportsApiInterface
     */
    saveSampleReportRaw(requestParameters: SaveSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>>;

    /**
     * Saves a preliminary diagnostic report
     */
    saveSampleReport(requestParameters: SaveSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample>;

}

/**
 * 
 */
export class SampleReportsApi extends runtime.BaseAPI implements SampleReportsApiInterface {

    /**
     * Discards a preliminary diagnostic report
     */
    async deleteSampleReportRaw(requestParameters: DeleteSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>> {
        if (requestParameters.sampleId === null || requestParameters.sampleId === undefined) {
            throw new runtime.RequiredError('sampleId','Required parameter requestParameters.sampleId was null or undefined when calling deleteSampleReport.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/samples/{sampleId}/report`.replace(`{${"sampleId"}}`, encodeURIComponent(String(requestParameters.sampleId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleFromJSON(jsonValue));
    }

    /**
     * Discards a preliminary diagnostic report
     */
    async deleteSampleReport(requestParameters: DeleteSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample> {
        const response = await this.deleteSampleReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Finalizes the diagnostic report
     */
    async finalizeSampleReportRaw(requestParameters: FinalizeSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>> {
        if (requestParameters.sampleId === null || requestParameters.sampleId === undefined) {
            throw new runtime.RequiredError('sampleId','Required parameter requestParameters.sampleId was null or undefined when calling finalizeSampleReport.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/samples/{sampleId}/report/finalize`.replace(`{${"sampleId"}}`, encodeURIComponent(String(requestParameters.sampleId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleFromJSON(jsonValue));
    }

    /**
     * Finalizes the diagnostic report
     */
    async finalizeSampleReport(requestParameters: FinalizeSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample> {
        const response = await this.finalizeSampleReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Saves a preliminary diagnostic report
     */
    async saveSampleReportRaw(requestParameters: SaveSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>> {
        if (requestParameters.sampleId === null || requestParameters.sampleId === undefined) {
            throw new runtime.RequiredError('sampleId','Required parameter requestParameters.sampleId was null or undefined when calling saveSampleReport.');
        }

        if (requestParameters.reportDraft === null || requestParameters.reportDraft === undefined) {
            throw new runtime.RequiredError('reportDraft','Required parameter requestParameters.reportDraft was null or undefined when calling saveSampleReport.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/samples/{sampleId}/report`.replace(`{${"sampleId"}}`, encodeURIComponent(String(requestParameters.sampleId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ReportDraftToJSON(requestParameters.reportDraft),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleFromJSON(jsonValue));
    }

    /**
     * Saves a preliminary diagnostic report
     */
    async saveSampleReport(requestParameters: SaveSampleReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample> {
        const response = await this.saveSampleReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
