/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis Test List Api
 * Sample And Diagnosis Test List management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Condition,
} from '../models';
import {
    ConditionFromJSON,
    ConditionToJSON,
} from '../models';

export interface GetConditionsRequest {
    sampleAndDiagnosisId: string;
}

/**
 * SampleAndDiagnosisConditionsApi - interface
 * 
 * @export
 * @interface SampleAndDiagnosisConditionsApiInterface
 */
export interface SampleAndDiagnosisConditionsApiInterface {
    /**
     * By using sampleAndDiagnosisId you get list of predefined conditions
     * @summary Provides the list of conditions associated with sample and diagnosis
     * @param {string} sampleAndDiagnosisId pass the id of the particular sample and diagnosis
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleAndDiagnosisConditionsApiInterface
     */
    getConditionsRaw(requestParameters: GetConditionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Condition>>>;

    /**
     * By using sampleAndDiagnosisId you get list of predefined conditions
     * Provides the list of conditions associated with sample and diagnosis
     */
    getConditions(requestParameters: GetConditionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Condition>>;

}

/**
 * 
 */
export class SampleAndDiagnosisConditionsApi extends runtime.BaseAPI implements SampleAndDiagnosisConditionsApiInterface {

    /**
     * By using sampleAndDiagnosisId you get list of predefined conditions
     * Provides the list of conditions associated with sample and diagnosis
     */
    async getConditionsRaw(requestParameters: GetConditionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Condition>>> {
        if (requestParameters.sampleAndDiagnosisId === null || requestParameters.sampleAndDiagnosisId === undefined) {
            throw new runtime.RequiredError('sampleAndDiagnosisId','Required parameter requestParameters.sampleAndDiagnosisId was null or undefined when calling getConditions.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/test-list/{sampleAndDiagnosisId}/condition`.replace(`{${"sampleAndDiagnosisId"}}`, encodeURIComponent(String(requestParameters.sampleAndDiagnosisId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConditionFromJSON));
    }

    /**
     * By using sampleAndDiagnosisId you get list of predefined conditions
     * Provides the list of conditions associated with sample and diagnosis
     */
    async getConditions(requestParameters: GetConditionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Condition>> {
        const response = await this.getConditionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
