/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis Test List Api
 * Sample And Diagnosis Test List management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TestListEntry,
} from '../models';
import {
    TestListEntryFromJSON,
    TestListEntryToJSON,
} from '../models';

export interface GetTestListEntriesRequest {
    sampleAndDiagnosisId: string;
}

/**
 * SampleAndDiagnosisTestListApi - interface
 * 
 * @export
 * @interface SampleAndDiagnosisTestListApiInterface
 */
export interface SampleAndDiagnosisTestListApiInterface {
    /**
     * By using sampleAndDiagnosisId you get list of entries in sample and diagnosis test list
     * @summary Provides the sample and diagnosis test list
     * @param {string} sampleAndDiagnosisId pass the id of the particular sample and diagnosis
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleAndDiagnosisTestListApiInterface
     */
    getTestListEntriesRaw(requestParameters: GetTestListEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TestListEntry>>>;

    /**
     * By using sampleAndDiagnosisId you get list of entries in sample and diagnosis test list
     * Provides the sample and diagnosis test list
     */
    getTestListEntries(requestParameters: GetTestListEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TestListEntry>>;

}

/**
 * 
 */
export class SampleAndDiagnosisTestListApi extends runtime.BaseAPI implements SampleAndDiagnosisTestListApiInterface {

    /**
     * By using sampleAndDiagnosisId you get list of entries in sample and diagnosis test list
     * Provides the sample and diagnosis test list
     */
    async getTestListEntriesRaw(requestParameters: GetTestListEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TestListEntry>>> {
        if (requestParameters.sampleAndDiagnosisId === null || requestParameters.sampleAndDiagnosisId === undefined) {
            throw new runtime.RequiredError('sampleAndDiagnosisId','Required parameter requestParameters.sampleAndDiagnosisId was null or undefined when calling getTestListEntries.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/test-list/{sampleAndDiagnosisId}/entries`.replace(`{${"sampleAndDiagnosisId"}}`, encodeURIComponent(String(requestParameters.sampleAndDiagnosisId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TestListEntryFromJSON));
    }

    /**
     * By using sampleAndDiagnosisId you get list of entries in sample and diagnosis test list
     * Provides the sample and diagnosis test list
     */
    async getTestListEntries(requestParameters: GetTestListEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TestListEntry>> {
        const response = await this.getTestListEntriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
