/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  NewSample,
  Sample,
  SampleStatus,
  SampleStatusUpdate,
} from '../models';
import {
    NewSampleFromJSON,
    NewSampleToJSON,
    SampleFromJSON,
    SampleToJSON,
    SampleStatusFromJSON,
    SampleStatusToJSON,
    SampleStatusUpdateFromJSON,
    SampleStatusUpdateToJSON,
} from '../models';

export interface CreateSampleRequest {
    newSample: NewSample;
}

export interface DeleteSampleRequest {
    sampleId: string;
}

export interface GetSampleRequest {
    sampleId: string;
}

export interface GetSamplesRequest {
    status?: Array<SampleStatus>;
    patientId?: string;
    sampleCode?: string;
    testType?: string;
    includeTainted?: boolean;
}

export interface UpdateSampleRequest {
    sampleId: string;
    newSample: NewSample;
}

export interface UpdateSampleStatusRequest {
    sampleId: string;
    sampleStatusUpdate: SampleStatusUpdate;
}

/**
 * SamplesApi - interface
 * 
 * @export
 * @interface SamplesApiInterface
 */
export interface SamplesApiInterface {
    /**
     * 
     * @summary Creates a technician sample draft
     * @param {NewSample} newSample Sample draft metadata and selected test types.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SamplesApiInterface
     */
    createSampleRaw(requestParameters: CreateSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>>;

    /**
     * Creates a technician sample draft
     */
    createSample(requestParameters: CreateSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample>;

    /**
     * Finalized samples are retained as patient documentation and cannot be deleted.
     * @summary Deletes a non-finalized sample
     * @param {string} sampleId System identifier of the sample.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SamplesApiInterface
     */
    deleteSampleRaw(requestParameters: DeleteSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Finalized samples are retained as patient documentation and cannot be deleted.
     * Deletes a non-finalized sample
     */
    deleteSample(requestParameters: DeleteSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Provides sample detail
     * @param {string} sampleId System identifier of the sample.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SamplesApiInterface
     */
    getSampleRaw(requestParameters: GetSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>>;

    /**
     * Provides sample detail
     */
    getSample(requestParameters: GetSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample>;

    /**
     * 
     * @summary Provides samples
     * @param {Array<SampleStatus>} [status] Optional comma-separated status filter.
     * @param {string} [patientId] Optional patient identifier filter.
     * @param {string} [sampleCode] Optional visible sample code filter.
     * @param {string} [testType] Optional test type code filter.
     * @param {boolean} [includeTainted] Includes tainted samples when true.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SamplesApiInterface
     */
    getSamplesRaw(requestParameters: GetSamplesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Sample>>>;

    /**
     * Provides samples
     */
    getSamples(requestParameters: GetSamplesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Sample>>;

    /**
     * Updates sample metadata before it is published to diagnostics.
     * @summary Updates a technician draft sample
     * @param {string} sampleId System identifier of the sample.
     * @param {NewSample} newSample Replacement sample metadata.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SamplesApiInterface
     */
    updateSampleRaw(requestParameters: UpdateSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>>;

    /**
     * Updates sample metadata before it is published to diagnostics.
     * Updates a technician draft sample
     */
    updateSample(requestParameters: UpdateSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample>;

    /**
     * 
     * @summary Updates sample status
     * @param {string} sampleId System identifier of the sample.
     * @param {SampleStatusUpdate} sampleStatusUpdate Requested status transition.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SamplesApiInterface
     */
    updateSampleStatusRaw(requestParameters: UpdateSampleStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>>;

    /**
     * Updates sample status
     */
    updateSampleStatus(requestParameters: UpdateSampleStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample>;

}

/**
 * 
 */
export class SamplesApi extends runtime.BaseAPI implements SamplesApiInterface {

    /**
     * Creates a technician sample draft
     */
    async createSampleRaw(requestParameters: CreateSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>> {
        if (requestParameters.newSample === null || requestParameters.newSample === undefined) {
            throw new runtime.RequiredError('newSample','Required parameter requestParameters.newSample was null or undefined when calling createSample.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/samples`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewSampleToJSON(requestParameters.newSample),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleFromJSON(jsonValue));
    }

    /**
     * Creates a technician sample draft
     */
    async createSample(requestParameters: CreateSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample> {
        const response = await this.createSampleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Finalized samples are retained as patient documentation and cannot be deleted.
     * Deletes a non-finalized sample
     */
    async deleteSampleRaw(requestParameters: DeleteSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.sampleId === null || requestParameters.sampleId === undefined) {
            throw new runtime.RequiredError('sampleId','Required parameter requestParameters.sampleId was null or undefined when calling deleteSample.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/samples/{sampleId}`.replace(`{${"sampleId"}}`, encodeURIComponent(String(requestParameters.sampleId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Finalized samples are retained as patient documentation and cannot be deleted.
     * Deletes a non-finalized sample
     */
    async deleteSample(requestParameters: DeleteSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSampleRaw(requestParameters, initOverrides);
    }

    /**
     * Provides sample detail
     */
    async getSampleRaw(requestParameters: GetSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>> {
        if (requestParameters.sampleId === null || requestParameters.sampleId === undefined) {
            throw new runtime.RequiredError('sampleId','Required parameter requestParameters.sampleId was null or undefined when calling getSample.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/samples/{sampleId}`.replace(`{${"sampleId"}}`, encodeURIComponent(String(requestParameters.sampleId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleFromJSON(jsonValue));
    }

    /**
     * Provides sample detail
     */
    async getSample(requestParameters: GetSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample> {
        const response = await this.getSampleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Provides samples
     */
    async getSamplesRaw(requestParameters: GetSamplesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Sample>>> {
        const queryParameters: any = {};

        if (requestParameters.status) {
            queryParameters['status'] = requestParameters.status.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.patientId !== undefined) {
            queryParameters['patientId'] = requestParameters.patientId;
        }

        if (requestParameters.sampleCode !== undefined) {
            queryParameters['sampleCode'] = requestParameters.sampleCode;
        }

        if (requestParameters.testType !== undefined) {
            queryParameters['testType'] = requestParameters.testType;
        }

        if (requestParameters.includeTainted !== undefined) {
            queryParameters['includeTainted'] = requestParameters.includeTainted;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/samples`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SampleFromJSON));
    }

    /**
     * Provides samples
     */
    async getSamples(requestParameters: GetSamplesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Sample>> {
        const response = await this.getSamplesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates sample metadata before it is published to diagnostics.
     * Updates a technician draft sample
     */
    async updateSampleRaw(requestParameters: UpdateSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>> {
        if (requestParameters.sampleId === null || requestParameters.sampleId === undefined) {
            throw new runtime.RequiredError('sampleId','Required parameter requestParameters.sampleId was null or undefined when calling updateSample.');
        }

        if (requestParameters.newSample === null || requestParameters.newSample === undefined) {
            throw new runtime.RequiredError('newSample','Required parameter requestParameters.newSample was null or undefined when calling updateSample.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/samples/{sampleId}`.replace(`{${"sampleId"}}`, encodeURIComponent(String(requestParameters.sampleId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NewSampleToJSON(requestParameters.newSample),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleFromJSON(jsonValue));
    }

    /**
     * Updates sample metadata before it is published to diagnostics.
     * Updates a technician draft sample
     */
    async updateSample(requestParameters: UpdateSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample> {
        const response = await this.updateSampleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates sample status
     */
    async updateSampleStatusRaw(requestParameters: UpdateSampleStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>> {
        if (requestParameters.sampleId === null || requestParameters.sampleId === undefined) {
            throw new runtime.RequiredError('sampleId','Required parameter requestParameters.sampleId was null or undefined when calling updateSampleStatus.');
        }

        if (requestParameters.sampleStatusUpdate === null || requestParameters.sampleStatusUpdate === undefined) {
            throw new runtime.RequiredError('sampleStatusUpdate','Required parameter requestParameters.sampleStatusUpdate was null or undefined when calling updateSampleStatus.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/samples/{sampleId}/status`.replace(`{${"sampleId"}}`, encodeURIComponent(String(requestParameters.sampleId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SampleStatusUpdateToJSON(requestParameters.sampleStatusUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleFromJSON(jsonValue));
    }

    /**
     * Updates sample status
     */
    async updateSampleStatus(requestParameters: UpdateSampleStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample> {
        const response = await this.updateSampleStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
