/* tslint:disable */
/* eslint-disable */
/**
 * Sample And Diagnosis API
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TestType,
} from '../models';
import {
    TestTypeFromJSON,
    TestTypeToJSON,
} from '../models';

/**
 * TestTypesApi - interface
 * 
 * @export
 * @interface TestTypesApiInterface
 */
export interface TestTypesApiInterface {
    /**
     * 
     * @summary Provides supported test types
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestTypesApiInterface
     */
    getTestTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TestType>>>;

    /**
     * Provides supported test types
     */
    getTestTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TestType>>;

}

/**
 * 
 */
export class TestTypesApi extends runtime.BaseAPI implements TestTypesApiInterface {

    /**
     * Provides supported test types
     */
    async getTestTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TestType>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/test-types`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TestTypeFromJSON));
    }

    /**
     * Provides supported test types
     */
    async getTestTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TestType>> {
        const response = await this.getTestTypesRaw(initOverrides);
        return await response.value();
    }

}
